apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-copy-secrets
  namespace: kafka-cluster
  labels:
    component: k8s-copy-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      component: k8s-copy-secrets
  template:
    metadata:
      name: k8s-copy-secrets
      labels:
        component: k8s-copy-secrets
    spec:
      serviceAccountName: k8s-copy-secrets
      containers:
        - name: k8s-copy-secrets
          image: 'azapps/k8s-copy-secrets:latest'
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
                cpu: "100m"
                memory: "100Mi"
          env:
            - name: DEBUG
              value: "*"
            - name: NAMESPACE
              value: "kafka-cluster"
