kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-copy-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-copy-secrets
  namespace: kafka-cluster
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-copy-secrets
subjects:
- kind: ServiceAccount
  name: k8s-copy-secrets
  namespace: kafka-cluster
roleRef:
  kind: ClusterRole
  name: k8s-copy-secrets
  apiGroup: rbac.authorization.k8s.io
