apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      tls:
        authentication:
          type: tls
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 10Gi
      class: standard
    resources:
      requests:
        cpu: 500m
        memory: 1G
      limit:
        cpu: 4000m
        memory: 10G
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    resources:
      requests:
        cpu: 500m
        memory: 300M
      limit:
        cpu: 1
        memory: 1G
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limit:
          cpu: 100m
          memory: 100M
    userOperator:
        requests:
          cpu: 100m
          memory: 100M
        limit:
          cpu: 100m
          memory: 100M
